###
POST http://172.18.0.3:8080/api/user
Content-Type: application/json

{
  "username": "username3",
  "password": "password",
  "email": "email4",
  "firstName": "firstName",
  "lastName": "lastName"
}

###
GET http://localhost:8080/api/user

###
GET http://localhost:8080/api/user/1

###
DELETE http://localhost:8080/api/user/3