###
POST http://localhost:8080/api/user
Content-Type: application/json

{
  "username": "username2",
  "password": "password",
  "email": "email2",
  "firstName": "firstName",
  "lastName": "lastName"
}

###
GET http://localhost:8080/api/user

###
GET http://localhost:8080/api/user/1

###
DELETE http://localhost:8080/api/user/3